" ~/.vim/vimrc

filetype plugin indent on

syntax on

set backspace=indent,eol,start
set hidden
set noswapfile
set colorcolumn=80
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set autoindent
set smartindent
