#!/usr/bin/env bash 

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -CGb &
pgrep -x polybar > /dev/null || polybar main &
pgrep -x feh > /dev/null || feh --bg-fill --randomize ~/Bilder* &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width 0
bspc config window_gap 16

bspc config borderless_monocle true
bspc config gapless_monocle true
